on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: config env
        run: cp .env.example .env
      - name: test
        run: docker-compose up